#!/bin/sh

case "$1" in
    start)
        /bin/scull_load
        /bin/module_load faulty
        modprobe hello
        ;;
    stop)
        /bin/scull_unload
        /bin/module_unload faulty
        rmmod hello
        ;;
    *)
        echo "Usage: $0 { start | stop }"
        exit 1
esac

exit 0
