name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container:
          image: cuaesd/aesd-autotest:24-assignment7-buildroot
          volumes:
            - /home/domenic/.cache/br2/ccache:/br2/ccache
            - /home/domenic/.cache/br2/dl:/br2/dl
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              BR2_CCACHE_DIR: /br2/ccache
              BR2_DL_DIR: /br2/dl
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
